# Generated by Django 2.2.16 on 2020-10-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('phone', models.CharField(max_length=255, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('address', models.TextField(max_length=2000, verbose_name='Адрес')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('href', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('desc', models.CharField(blank=True, max_length=8000, verbose_name='Описание')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('desc', models.CharField(blank=True, max_length=8000, verbose_name='Описание')),
                ('image_src', models.ImageField(blank=True, upload_to='products_images')),
                ('image_href', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол-во на складе')),
                ('alt', models.CharField(blank=True, max_length=8000, verbose_name='Текст картинки')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.ProductsCategory')),
            ],
        ),
    ]
