# Generated by Django 2.2.16 on 2020-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_href',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
