# Generated by Django 2.2.16 on 2020-10-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201009_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductsCategory',
        ),
    ]
