# Generated by Django 2.2.16 on 2020-10-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fill_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='категория активна'),
        ),
    ]
