# Generated by Django 2.2.16 on 2020-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201009_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(blank=True, max_length=8000, verbose_name='Текст картинки'),
        ),
    ]
