# Generated by Django 2.2.16 on 2020-10-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_href',
            new_name='image_href',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img_src',
            new_name='image_src',
        ),
    ]
