# Generated by Django 2.2.16 on 2020-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201009_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscategory',
            name='href',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
