# Generated by Django 2.2.16 on 2020-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_productscategory_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('phone', models.CharField(max_length=255, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('address', models.TextField(max_length=2000, verbose_name='Адрес')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
    ]
