# Generated by Django 2.2.16 on 2020-10-12 08:30
import os
from django.db import migrations


def forwards_func(apps, schema_editor):
    os.system('python manage.py loaddata Contact');
    os.system('python manage.py loaddata ProductsCategory');
    os.system('python manage.py loaddata Product');


def reverse_func(apps, schema_editor):
    myModels = [apps.get_model("mainapp", "Product")
        , apps.get_model("mainapp", "Contact")
        , apps.get_model("mainapp", "ProductsCategory")]

    # Delete all objects
    for myModel in myModels:
        myModel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0007_contact'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)
                  ]
